/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.1.1-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package mil.nga.elevation_services.api;

import mil.nga.elevation_services.model.Error;
import mil.nga.elevation_services.model.MinMaxElevationQuery;
import mil.nga.elevation_services.model.MinMaxElevationResponse;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-08-29T11:50:00.502Z[Etc/GMT-0]")

@Validated
@Api(value = "MinMaxElevation", description = "the MinMaxElevation API")
public interface MinMaxElevationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "Determine the minium and maximum elevation height values within a particular bounding box.", nickname = "getElevationAtPOST", notes = "", response = MinMaxElevationResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Elevation data requested.", response = MinMaxElevationResponse.class),
        @ApiResponse(code = 200, message = "unexpected error", response = Error.class) })
    @RequestMapping(value = "/MinMaxElevation",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<MinMaxElevationResponse> getElevationAtPOST(@ApiParam(value = "Client specified bounding box.  The coordinates can be specified in either DMS format or decimal degrees." ,required=true )  @Valid @RequestBody MinMaxElevationQuery minMaxElevationQuery) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"security\" : {    \"ownerProducer\" : \"ownerProducer\",    \"classification\" : \"classification\"  },  \"minElevation\" : {    \"elevation\" : 0,    \"coordinate\" : {      \"lon\" : 7.061401241503109,      \"lat\" : 2.3021358869347655    },    \"absHorizontalAccuracy\" : 6,    \"relHorizontalAccuracy\" : 5,    \"absVerticalAccuracy\" : 1,    \"relVerticalAccuracy\" : 5  },  \"maxElevation\" : {    \"elevation\" : 0,    \"coordinate\" : {      \"lon\" : 7.061401241503109,      \"lat\" : 2.3021358869347655    },    \"absHorizontalAccuracy\" : 6,    \"relHorizontalAccuracy\" : 5,    \"absVerticalAccuracy\" : 1,    \"relVerticalAccuracy\" : 5  }}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "Determine the minium and maximum elevation height values within a particular bounding box.", nickname = "getMinMaxElevationAtGET", notes = "", response = MinMaxElevationResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The minimum and maximum elevation values within the user-specified bounding box.", response = MinMaxElevationResponse.class),
        @ApiResponse(code = 200, message = "unexpected error", response = Error.class) })
    @RequestMapping(value = "/MinMaxElevation",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<MinMaxElevationResponse> getMinMaxElevationAtGET(@NotNull @Size(min=4,max=4) @ApiParam(value = "A bounding box containing the southwest and northeast coordinates in lon, lat order.   The coordinates can be specified in either DMS format or decimal degrees.", required = true) @Valid @RequestParam(value = "bbox", required = true) List<String> bbox,@ApiParam(value = "The output units for the elevation height data.", allowableValues = "FEET, METERS", defaultValue = "METERS") @Valid @RequestParam(value = "heightType", required = false, defaultValue="METERS") String heightType,@ApiParam(value = "This parameter is no longer used.") @Valid @RequestParam(value = "operation", required = false) String operation) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"security\" : {    \"ownerProducer\" : \"ownerProducer\",    \"classification\" : \"classification\"  },  \"minElevation\" : {    \"elevation\" : 0,    \"coordinate\" : {      \"lon\" : 7.061401241503109,      \"lat\" : 2.3021358869347655    },    \"absHorizontalAccuracy\" : 6,    \"relHorizontalAccuracy\" : 5,    \"absVerticalAccuracy\" : 1,    \"relVerticalAccuracy\" : 5  },  \"maxElevation\" : {    \"elevation\" : 0,    \"coordinate\" : {      \"lon\" : 7.061401241503109,      \"lat\" : 2.3021358869347655    },    \"absHorizontalAccuracy\" : 6,    \"relHorizontalAccuracy\" : 5,    \"absVerticalAccuracy\" : 1,    \"relVerticalAccuracy\" : 5  }}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
