openapi: "3.0.0"
info:
  version: 1.0.0
  title: Elevation Services
  license:
    name: MIT
servers:
  - url: http://localhost/v1
paths:
  /ElevationAt:
    post:
      summary: Get the elevation at a particular point.
      operationId: "getElevationAt"
      requestBody:
        description: Client specified geographic point.
        required: true
        content:
          application/json:    
            schema:
              $ref: "#/components/schemas/ElevationQuery"
          application/xml:      
            schema:
              $ref: "#/components/schemas/ElevationQuery"
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: An paged array of pets
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ElevationResponse"
            application/xml:      
              schema:
                $ref: "#/components/schemas/ElevationResponse"
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    ElevationHeightType:
      type: string
      default: METERS
      enum: 
        - FEET
        - METERS
      description: >
        Output Elevation Units:
          * FEET - Output elevation in feet.
          * METERS - Output elevation in meters (default)
    SourceDEMType:
      type: string
      default: DTED0
      enum:
        - DTED2
        - DTED1
        - DTED0
        - SRTM2
        - SRTM1
        - SRTM2F
        - SRTM1F
        - BEST
    ElevationQuery:
      type: object
      properties:
        heightType:
          $ref: '#/components/schemas/ElevationHeightType'
        source:
          $ref: '#/components/schemas/SourceDEMType'
    ElevationResponse:
      type: object
      properties:
        heightType:
          $ref: '#/components/schemas/ElevationHeightType'
        source:
          $ref: '#/components/schemas/SourceDEMType'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string